name: TotalEssentials
version: 1.2.2
main: github.gilbertokpl.total.TotalEssentials
author: Gilberto
api-version: 1.13
folia-supported: true
softdepend:
  - Vault
  - Multiverse-Core
  - EverNifeCore
  - LegendChat