name: TotalEssentials
version: 1.2.3
main: github.gilbertokpl.total.TotalEssentials
author: Gilberto
api-version: 1.13
folia-supported: true
softdepend:
  - Vault
  - PlaceholderAPI
  - Citizens
  - Multiverse-Core
  - EverNifeCore
permissions:
  totalessentials.commands.tell:
    default: true
  totalessentials.chat.reload:
    default: op
  totalessentials.chat.bypass.cooldown:
    default: op
